# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE LOCAL (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:cmmsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=cmms-super-secret-key-para-jwt-256bits-segura-2026
jwt.expiration=86400000

# ===============================
# CACHE (Caffeine)
# ===============================
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=300s

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
info.app.name=CMMS Industrial Suite
info.app.version=1.0.0
info.app.description=Sistema de Gerenciamento de Manutenção Industrial
